### ISSUE TITLE
Watermark image only showing up on the last page

### ISSUE THREAD

**Issue by lxkraken** [niklasravnsborg/laravel-pdf#61] opened 2017-10-13 17:51 UTC
Hi,

As the code stands now, the watermark image will only appear on the final page of a generated PDF using the SetWatermarkImage() function.

I did, however, manage to get the watermark showing up on every page by inserting these two lines of code in the constructor of your Pdf class:

```
$this->mpdf->showWatermarkImage = true;
$this->mpdf->setWatermarkImage('watermark.png', 0.2, 'F', 'F');
```

Anyhow, I'm not entirely sure where exactly the problem is, but hopefully this will give you a clue. Thanks again!

**Comment by niklasravnsborg** [comment] 2017-10-25 10:00
This is a duplicate of https://github.com/niklasravnsborg/laravel-pdf/issues/61, right?

**Closed by niklasravnsborg** 2017-10-25 10:00 UTC

**Comment by Adcaelo** [comment] 2018-11-08 09:18
duplicate of #45  not 61 (self)
